FROM node:22-slim

LABEL org.opencontainers.image.authors="DarkMatter999"
LABEL org.opencontainers.image.title="Peer"
LABEL org.opencontainers.image.description="DHT Peer"
LABEL org.opencontainers.image.vendor="DarkMatter999"

WORKDIR /opt/app

RUN npm install -g node-pre-gyp

COPY package*.json ./
RUN npm install

COPY . .

ENV SIGNALLING_PORT=3000
ENV SIGNALLING_HOST=signalling

CMD ["npm", "run", "peer"]
