FROM node:22-slim

LABEL org.opencontainers.image.authors="DarkMatter999"
LABEL org.opencontainers.image.title="Signalling Server"
LABEL org.opencontainers.image.description="DHT WebSocket signalling server"
LABEL org.opencontainers.image.vendor="DarkMatter999"

WORKDIR /opt/app

RUN npm install -g node-pre-gyp

COPY package*.json ./
RUN npm install

COPY . .

ENV SIGNALLING_PORT=3000
EXPOSE ${SIGNALLING_PORT}

CMD ["npm", "run", "signalling"]
